version: '3'

services:

  oeplannerapi:
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - CELERY_RESULTS_BACKEND_URL=rpc://
    build:
      context: src/backend
      dockerfile: oeplannerapi/Dockerfile
    ports:
      - "8080:80"

  oeplannerworker:
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - CELERY_RESULTS_BACKEND_URL=rpc://
    build:
      context: src/backend/oeplannerworker
      dockerfile: Dockerfile

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - CELERY_RESULTS_BACKEND_URL=rpc://
      - FLOWER_PORT=5555

  rabbitmq:
      image: rabbitmq:3-management
      ports:
        - "5672:5672"
        - "15672:15672"